"""Public façade for the Bellatrex NiceGUI explorer.

This module keeps the public API stable while delegating implementation to the
private ``bellatrex._nicegui`` package.
"""

import argparse


def plot_with_interface(*args, **kwargs):
    """Prepare plot data for the NiceGUI interactive frontend."""
    from ._nicegui.rendering import plot_with_interface as _plot_with_interface

    return _plot_with_interface(*args, **kwargs)


def launch_nicegui_window(*args, **kwargs):
    """Open the Bellatrex NiceGUI explorer."""
    from ._nicegui.windows import launch_nicegui_window as _launch_nicegui_window

    return _launch_nicegui_window(*args, **kwargs)


def _serve_payload_file(payload_path: str) -> None:
    from ._nicegui.runtime import serve_payload_file

    serve_payload_file(payload_path)


def _parse_cli_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run the Bellatrex NiceGUI window.")
    parser.add_argument("--payload", required=True, help="Pickle payload generated by Bellatrex.")
    return parser.parse_args()


__all__ = ["plot_with_interface", "launch_nicegui_window"]


if __name__ == "__main__":
    _serve_payload_file(_parse_cli_args().payload)
